//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRM_PEDIDO_VENDA_ITEM
    {
        public int CRPI_CD_ID { get; set; }
        public int CRPV_CD_ID { get; set; }
        public Nullable<int> PROD_CD_ID { get; set; }
        public Nullable<int> UNID_CD_ID { get; set; }
        public int CRPI_IN_QUANTIDADE { get; set; }
        public Nullable<decimal> CRPI_VL_PRECO_AJUSTADO { get; set; }
        public Nullable<decimal> CRPI_VL_PRECO_TOTAL { get; set; }
        public Nullable<decimal> CRPI_VL_MARKUP { get; set; }
        public string CRPI_TX_OBSERVACAO { get; set; }
        public Nullable<System.DateTime> CRPI_DT_JUSTIFICATIVA { get; set; }
        public string CRPI_DS_JUSTIFICATIVA { get; set; }
        public int CRPI_IN_ATIVO { get; set; }
        public Nullable<int> CRPI_IN_QUANTIDADE_REVISADA { get; set; }
        public Nullable<decimal> CRPI_VL_DESCONTO { get; set; }
        public Nullable<int> CRPI_IN_TIPO_ITEM { get; set; }
        public Nullable<int> SERV_CD_ID { get; set; }
        public Nullable<int> CRPI_IN_DIFERENCA { get; set; }
    
        public virtual CRM_PEDIDO_VENDA CRM_PEDIDO_VENDA { get; set; }
        public virtual PRODUTO PRODUTO { get; set; }
        public virtual UNIDADE UNIDADE { get; set; }
    }
}
