//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRM_COMENTARIO
    {
        public int CRCM_CD_ID { get; set; }
        public int CRM1_CD_ID { get; set; }
        public int USUA_CD_ID { get; set; }
        public Nullable<System.DateTime> CRCM_DT_COMENTARIO { get; set; }
        public string CRCM_DS_COMENTARIO { get; set; }
        public Nullable<int> CRCM_IN_ATIVO { get; set; }
    
        public virtual CRM CRM { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
