//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPRESA_CUSTO_VARIAVEL
    {
        public int EMCV_CD_ID { get; set; }
        public Nullable<int> EMPR_CD_ID { get; set; }
        public string EMCV_NM_NOME { get; set; }
        public Nullable<decimal> EMCV_VL_VALOR { get; set; }
        public Nullable<int> EMCV_IN_ATIVO { get; set; }
    
        public virtual EMPRESA EMPRESA { get; set; }
    }
}
