//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FICHA_TECNICA
    {
        public int FITE_CD_ID { get; set; }
        public int PROD_CD_ID { get; set; }
        public Nullable<int> ASSI_CD_ID { get; set; }
        public string FITE_AQ_FOTO_APRESENTACAO { get; set; }
        public string FITE_NM_NOME { get; set; }
        public string FITE_DS_DESCRICAO { get; set; }
        public string FITE_DS_APRESENTACAO { get; set; }
        public Nullable<int> FITE_NR_PORCOES { get; set; }
        public Nullable<decimal> FITE_NR_PESO { get; set; }
        public Nullable<decimal> FITE_NR_FATOR_CORRECAO { get; set; }
        public Nullable<decimal> FITE_QN_QUANTIDADE_LIQUIDA { get; set; }
        public Nullable<decimal> FITE_PC_PERCENTUAL_PERDA { get; set; }
        public Nullable<System.DateTime> FITE_DT_CADASTRO { get; set; }
        public Nullable<int> FITE_IN_ATIVO { get; set; }
    
        public virtual PRODUTO PRODUTO { get; set; }
    }
}
