//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PESSOA_EXTERNA_ANEXO
    {
        public int PEAX_CD_ID { get; set; }
        public int PEEX_CD_ID { get; set; }
        public string PEAX_NM_TITULO { get; set; }
        public Nullable<System.DateTime> PEAX_DT_ANEXO { get; set; }
        public Nullable<int> PEAX_IN_TIPO { get; set; }
        public string PEAX_AQ_ARQUIVO { get; set; }
        public int PEAX_IN_ATIVO { get; set; }
    
        public virtual PESSOA_EXTERNA PESSOA_EXTERNA { get; set; }
    }
}
