//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PESSOA_EXTERNA
    {
        public int PEEX_CD_ID { get; set; }
        public int ASSI_CD_ID { get; set; }
        public int CARG_CD_ID { get; set; }
        public string PEEX_NM_NOME { get; set; }
        public string PEEX_NR_CPF { get; set; }
        public string PEEX_NR_RG { get; set; }
        public string PEES_EM_EMAIL { get; set; }
        public string PEEX_NR_TELEFONE { get; set; }
        public string PEEX_NR_CELULAR { get; set; }
        public System.DateTime PEEX_DT_CADASTRO { get; set; }
        public int PEEX_IN_ATIVO { get; set; }
    
        public virtual ASSINANTE ASSINANTE { get; set; }
        public virtual CARGO_USUARIO CARGO_USUARIO { get; set; }
    }
}
