//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PESSOA_EXTERNA_ANOTACAO
    {
        public int PEAN_CD_ID { get; set; }
        public int PEEX_CD_ID { get; set; }
        public int USUA_CD_ID { get; set; }
        public System.DateTime PEAN_DT_ANOTACAO { get; set; }
        public string PEAN_TX_ANOTACAO { get; set; }
        public int PEAN_IN_ATIVO { get; set; }
    
        public virtual PESSOA_EXTERNA PESSOA_EXTERNA { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
