//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUTO_TABELA_PRECO
    {
        public int PRTP_CD_ID { get; set; }
        public int PROD_CD_ID { get; set; }
        public Nullable<int> EMPR_CD_ID { get; set; }
        public Nullable<decimal> PRTP_VL_PRECO { get; set; }
        public Nullable<decimal> PRTP_VL_PRECO_PROMOCAO { get; set; }
        public Nullable<decimal> PRTP_VL_DESCONTO_MAXIMO { get; set; }
        public Nullable<decimal> PRTP_VL_MARKUP { get; set; }
        public Nullable<decimal> PRTP_VL_CUSTO { get; set; }
        public Nullable<System.DateTime> PRTP_DT_REAJUSTE { get; set; }
        public Nullable<int> PRTP_IN_ATIVO { get; set; }
    
        public virtual EMPRESA EMPRESA { get; set; }
        public virtual PRODUTO PRODUTO { get; set; }
    }
}
