//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUTO_ESTOQUE_EMPRESA
    {
        public int PREE_CD_ID { get; set; }
        public int PROD_CD_ID { get; set; }
        public int EMPR_CD_ID { get; set; }
        public decimal PREE_QN_ESTOQUE { get; set; }
        public System.DateTime PREE_DT_ULTIMO_MOVIMENTO { get; set; }
        public Nullable<decimal> PREF_QN_QUANTIDADE_ALTERADA { get; set; }
        public string PREE_DS_JUSTIFICATIVA { get; set; }
        public Nullable<decimal> PREE_VL_MARKUP { get; set; }
        public Nullable<decimal> PREE_QN_QUANTIDADE_RESERVADA { get; set; }
    
        public virtual EMPRESA EMPRESA { get; set; }
        public virtual PRODUTO PRODUTO { get; set; }
    }
}
