//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUTO_TABELA_PRECO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUTO_TABELA_PRECO()
        {
            this.FICHA_TECNICA = new HashSet<FICHA_TECNICA>();
            this.FICHA_TECNICA_DETALHE = new HashSet<FICHA_TECNICA_DETALHE>();
        }
    
        public int PRTP_CD_ID { get; set; }
        public int PROD_CD_ID { get; set; }
        public int EMPR_CD_ID { get; set; }
        public Nullable<decimal> PRTP_VL_PRECO { get; set; }
        public Nullable<decimal> PRTP_VL_PRECO_PROMOCAO { get; set; }
        public Nullable<decimal> PRTP_VL_DESCONTO_MAXIMO { get; set; }
        public Nullable<decimal> PRTP_VL_MARKUP { get; set; }
        public Nullable<System.DateTime> PRTP_DT_REAJUSTE { get; set; }
        public Nullable<int> PRTP_IN_ATIVO { get; set; }
    
        public virtual EMPRESA EMPRESA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FICHA_TECNICA> FICHA_TECNICA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FICHA_TECNICA_DETALHE> FICHA_TECNICA_DETALHE { get; set; }
        public virtual PRODUTO PRODUTO { get; set; }
    }
}
