//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUTO_ULTIMOS_CUSTOS
    {
        public int PRUC_CD_ID { get; set; }
        public int PROD_CD_ID { get; set; }
        public Nullable<System.DateTime> PRUC_DT_DATA_COMPRA { get; set; }
        public Nullable<decimal> PRUC_VL_VALOR_COMPRA { get; set; }
        public Nullable<int> PRUC_IN_ATIVO { get; set; }
    
        public virtual PRODUTO PRODUTO { get; set; }
    }
}
