//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUBGRUPO_PLANO_CONTA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SUBGRUPO_PLANO_CONTA()
        {
            this.PLANO_CONTA = new HashSet<PLANO_CONTA>();
        }
    
        public int SGCC_CD_ID { get; set; }
        public Nullable<int> ASSI_CD_ID { get; set; }
        public int GRCC_CD_ID { get; set; }
        public string SGCC_NR_NUMERO { get; set; }
        public string SGCC_NM_NOME { get; set; }
        public string SGCC_DS_DESCRICAO { get; set; }
        public Nullable<int> SGCC_IN_ATIVO { get; set; }
        public string SGCC_NM_EXIBE { get; set; }
    
        public virtual ASSINANTE ASSINANTE { get; set; }
        public virtual GRUPO_PLANO_CONTA GRUPO_PLANO_CONTA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PLANO_CONTA> PLANO_CONTA { get; set; }
    }
}
