//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMPLATE_SMS
    {
        public int TSMS_CD_ID { get; set; }
        public Nullable<int> ASSI_CD_ID { get; set; }
        public string TSMS_NM_NOME { get; set; }
        public string TSMS_SG_SIGLA { get; set; }
        public string TSMS_TX_CORPO { get; set; }
        public string TSMS_LK_LINK { get; set; }
        public int TSMS_IN_ATIVO { get; set; }
        public Nullable<int> TSMS_IN_EDITAVEL { get; set; }
    
        public virtual ASSINANTE ASSINANTE { get; set; }
    }
}
