//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMPLATE_EMAIL
    {
        public int TEEM_CD_ID { get; set; }
        public Nullable<int> ASSI_CD_ID { get; set; }
        public string TEEM_NM_NOME { get; set; }
        public string TEEM_SG_SIGLA { get; set; }
        public string TEEM_LK_LINK { get; set; }
        public Nullable<int> TEEM_IN_ATIVO { get; set; }
        public string TEEM_TX_CABECALHO { get; set; }
        public string TEEM_TX_CORPO { get; set; }
        public string TEEM_TX_DADOS { get; set; }
        public string TEEM_AQ_ARQUIVO { get; set; }
        public string TEEM_TX_COMPLETO { get; set; }
        public Nullable<int> TEEM_IN_HTML { get; set; }
        public Nullable<int> TEEM_IN_EDITAVEL { get; set; }
    
        public virtual ASSINANTE ASSINANTE { get; set; }
    }
}
