//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIDEO
    {
        public int VIDE_CD_ID { get; set; }
        public int ASSI_CD_ID { get; set; }
        public string VIDE_NM_TITULO { get; set; }
        public string VIDE_NM_DESCRICAO { get; set; }
        public string VIDE_AQ_FOTO { get; set; }
        public string VIDE_LK_LINK { get; set; }
        public System.DateTime VIDE_DT_EMISSAO { get; set; }
        public System.DateTime VIDE_DT_VALIDADE { get; set; }
        public int VIDE_NR_ACESSOS { get; set; }
        public string VIDE_NM_AUTOR { get; set; }
        public int VIDE_IN_ATIVO { get; set; }
    
        public virtual ASSINANTE ASSINANTE { get; set; }
    }
}
